// import Head from "next/head";
// <Head>
// <title>Create Next App</title>
// <meta name="description" content="Generated by create next app" />
// <meta name="viewport" content="width=device-width, initial-scale=1" />
// <link rel="icon" href="/favicon.ico" />
// </Head>

import React, { useState, useEffect } from "react";
import Image from "next/image";
import Navbar from "../comps/Navbar";
import img_1 from "../resources/images/card.jpeg";
import WHITE_DECORATION from "../resources/decorations/white-decoration.svg";
import TabCmp from "../comps/TabCmp";
import { Modal } from "react-responsive-modal";
import "react-responsive-modal/styles.css";
import MTN from "../resources/images/mtn.png";
import AIRTEL from "../resources/images/airtel.png";
import Footer from "../comps/Footer";
import Dropdown from "../comps/Dropdown";

const TABS = [
  { title: "1. Select Channel" },
  { title: "2. Payment Code" },
  { title: "3. Amount & phone" },
];

const LandingPage = () => {
  const [showPayNowSection, setShawPayNowSection] = useState(false);
  const [showSeachPaymentCode, setShowSeachPaymentCode] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [selected, setSelected] = useState("");
  const [selectedClass, setSelectedClass] = useState("");
  const [open, setOpen] = useState(false);

  useEffect(() => {
    console.log("@-selected school---", selected);
  }, [selected]);

  useEffect(() => {
    console.log("@-selected class: ", selectedClass);
  }, [selectedClass]);

  const onOpenModal = () => setOpen(true);
  const onCloseModal = () => setOpen(false);
  const stepChangeHandler = (stepNumber) => {
    setCurrentStep(stepNumber);
  };
  const onPaymentCodeSearchHandler = () => {
    setShawPayNowSection(false);
    setShowSeachPaymentCode(true);
  };
  const homeClickHandler = () => {
    setShawPayNowSection(false);
    setShowSeachPaymentCode(false);
  };
  return (
    <>
      <div className="landingPage">
        <Navbar
          onPaymentCodeSearchHandler={onPaymentCodeSearchHandler}
          onPaynowHandler={() => setShawPayNowSection(true)}
          homeClickHandler={homeClickHandler}
        />
        <div className="hero-container">
          <div className="hero-section container-small">
            {showPayNowSection && (
              <div className="paynowSection">
                <div className="paynowSection__header">
                  {TABS.map((el, index) => (
                    <div
                      className={`paynowSection__headerItem ${
                        currentStep === index ? "paynowSection__activeTab " : ""
                      } `}
                    >
                      {el.title}
                    </div>
                  ))}
                </div>
                <div className="paynowSection__formContainer">
                  {currentStep === 0 && (
                    <>
                      <div className="paynowSection__title getStartedPage__label">
                        Select payment method
                      </div>
                      <div className="paynowSection__paymentOption">
                        <div className="paynowSection__mobileOptions">
                          <div
                            onClick={() => stepChangeHandler(1)}
                            className="paynowSection__imgContainer"
                          >
                            <Image src={MTN} alt="school nestpay" />
                          </div>
                          <div
                            onClick={() => stepChangeHandler(1)}
                            className="paynowSection__imgContainer"
                          >
                            <Image src={AIRTEL} alt="school nestpay" />
                          </div>
                        </div>
                        {/* <div className="paynowSection__mobileOptions">
                          <img />
                        </div> */}
                      </div>
                    </>
                  )}
                  {currentStep === 1 && (
                    <div>
                      <div className="getStartedPage__textField">
                        <label className="getStartedPage__label">
                          Enter payment code/Reg No
                        </label>
                        <input
                          className="inputField"
                          type="text"
                          id="studentId"
                          name="studentId"
                        ></input>
                      </div>
                      <div className="btnContainer">
                        <div
                          onClick={() => stepChangeHandler(0)}
                          className="getStartedPage__formBtn backBtn"
                        >
                          Back
                        </div>
                        <div
                          onClick={() => stepChangeHandler(2)}
                          className="getStartedPage__formBtn proceedBtn"
                        >
                          Search
                        </div>
                      </div>
                    </div>
                  )}
                  {currentStep === 2 && (
                    <div>
                      <div className="getStartedPage__textField">
                        <label className="getStartedPage__label">
                          Enter amount
                        </label>
                        <input
                          className="inputField"
                          type="text"
                          id="feesAmount"
                          name="feesAmount"
                        ></input>
                      </div>
                      <div className="getStartedPage__textField">
                        <label className="getStartedPage__label">
                          Enter phone number
                        </label>
                        <input
                          className="inputField"
                          type="number"
                          id="phoneNumber"
                          name="phoneNumber"
                        ></input>
                      </div>
                      <div className="btnContainer">
                        <div
                          onClick={() => stepChangeHandler(1)}
                          className="getStartedPage__formBtn backBtn"
                        >
                          Back
                        </div>
                        <div
                          onClick={() => onOpenModal()}
                          className="getStartedPage__formBtn proceedBtn"
                        >
                          Proceed
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
            {!showPayNowSection && showSeachPaymentCode && (
              <>
                <div className="paynowSection">
                  <div className="paynowSection__formContainer">
                    <label className="getStartedPage__label">
                      Student payment code search
                    </label>
                    <div className="paynowSection__fieldsRow">
                      <div className="getStartedPage__textField">
                        <label className="getStartedPage__label">School</label>
                        {/* <input
                          className="inputField"
                          type="text"
                          id="studentId"
                          name="studentId"
                        ></input> */}
                        <Dropdown
                          selected={selected}
                          setSelected={setSelected}
                          options={["Auca", "Kist", "University of Kigali"]}
                        />
                      </div>
                      <div className="getStartedPage__textField">
                        <label className="getStartedPage__label">Class</label>
                        <Dropdown
                          selected={selectedClass}
                          setSelected={setSelectedClass}
                          options={["Senior 1", "Senior 2", "Senior 3"]}
                        />
                        {/* <input
                          className="inputField"
                          type="text"
                          id="studentId"
                          name="studentId"
                        ></input> */}
                      </div>
                    </div>
                    <div className="getStartedPage__textField">
                      <label className="getStartedPage__label">
                        Student name
                      </label>
                      <input
                        className="inputField"
                        type="text"
                        id="studentId"
                        name="studentId"
                      ></input>
                    </div>
                    <div
                      onClick={() => onOpenModal()}
                      className="getStartedPage__formBtn proceedBtn"
                    >
                      Search
                    </div>
                  </div>
                </div>
              </>
            )}

            {!showPayNowSection && !showSeachPaymentCode && (
              <>
                <h1 className="title-xl">SchoolFees payments made easier!</h1>
                <div className="flex">
                  <div className="left">
                    <div className="landingPage__imageContiner">
                      <Image src={img_1} alt="nestpay" />
                    </div>
                  </div>
                  <div className="right">
                    <p className="desc">
                      Pay school fees wherever you’re using one of the many
                      available payment channels on SchoolNest Pay
                    </p>
                    <div className="btn-dashed">
                      <div className="getStarted">Get started</div>
                    </div>
                  </div>
                </div>
              </>
            )}
          </div>
          <div className="decoration">
            <Image src={WHITE_DECORATION} alt="school nestpay" />
          </div>
          <div className="stats">
            <div className="stat">
              <h2>$0K</h2>
              <p>Transactions</p>
            </div>
            <div className="stat">
              <h2>3,581</h2>
              <p>Active Students</p>
            </div>
            <div className="stat">
              <h2>14</h2>
              <p>Active Schools</p>
            </div>
          </div>
        </div>
        <div className="why">
          <p className="title-xl">Why SchoolNest Pay?</p>
          <div className="container-small">
            <TabCmp />
          </div>
        </div>
        <Footer />

        <Modal
          classNames="getStartedPage__Modal"
          open={open}
          onClose={onCloseModal}
          center
        >
          <div className="modal__title">Student information</div>
          <div className="modal__details">
            <div className="modal__itemRow">
              <div className="modal__item">
                <div className="getStartedPage__label">Name:</div>
                <div className="modal__names modal__value">
                  BYIRINGIRO Jean Bien Aime
                </div>
              </div>
              <div className="modal__item">
                <div className="getStartedPage__label">Year:</div>
                <div className=" modal__value">S6</div>
              </div>
            </div>
            <div className="modal__itemRow">
              <div className="modal__item">
                <div className="getStartedPage__label">Amount</div>
                <div className="modal__names modal__value">150,000 Rwf</div>
              </div>
              <div className="modal__item">
                <div className="getStartedPage__label">School Name:</div>
                <div className=" modal__value">AUCA</div>
              </div>
            </div>
          </div>
          <div
            onClick={onCloseModal}
            className="getStartedPage__formBtn confirmBtn"
          >
            Confirm
          </div>
        </Modal>
      </div>
    </>
  );
};

export default LandingPage;
